version: "2"
linters:
  enable:
    - forcetypeassert
    - goconst
    - gocritic
    - godox
    - gosec
    - iface
    - intrange
    - musttag
    - nilnil
    - perfsprint
    - revive
    - sloglint
    - testifylint
    - thelper
    - tparallel
    - importas
  settings:
    goconst:
      ignore-calls: true
    gocritic:
      enable-all: true
      disabled-checks:
        - unnamedResult
    iface:
      enable:
        - identical
        - unused
    nilnil:
      detect-opposite: true
      checked-types:
        - chan
        - func
        - iface
        - map
        - ptr
        - uintptr
        - unsafeptr
    revive:
      confidence: 0.1
      rules:
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
          severity: error
          disabled: false
          exclude:
            - ""
        - name: early-return
          arguments:
            - preserveScope
            - allowJump
          severity: error
          disabled: false
          exclude:
            - ""
        - name: enforce-map-style
          arguments:
            - make
          severity: error
          disabled: false
          exclude:
            - ""
        - name: enforce-slice-style
          arguments:
            - make
          severity: error
          disabled: false
          exclude:
            - ""
        - name: filename-format
          arguments:
            - ^[_a-z][_a-z0-9]*.go$
          severity: error
          disabled: false
          exclude:
            - ""
        - name: optimize-operands-order
          severity: error
          disabled: false
          exclude:
            - ""
    sloglint:
      attr-only: false
      static-msg: true
      no-raw-keys: false
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source
        - foo
      args-on-sep-lines: true
    testifylint:
      enable-all: true
    importas:
      alias:
        - pkg: github.com/jacobbrewer1/web/cache
          alias: pkgcache
        - pkg: github.com/jacobbrewer1/web/slices
          alias: pkgslices
        - pkg: github.com/jacobbrewer1/web/sync
          alias: pkgsync
        - pkg: k8s.io/client-go/listers/core/v1
          alias: listersv1
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/api/apps/v1
          alias: appsv1
        - pkg: k8s.io/apimachinery/pkg/labels
          alias: k8slabels
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: k8serrors
        - pkg: k8s.io/api/events/v1
          alias: eventsv1
        - pkg: k8s.io/apimachinery/pkg/types
          alias: k8stypes
        - pkg: k8s.io/client-go/tools/cache
          alias: k8scache
        - pkg: github.com/oapi-codegen/runtime/types
          alias: oapi
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: (.+)_test.go
        text: ^(enforce-slice-style|enforce-map-style)
      - linters:
          - goconst
        path: (.+)_test\.go
      - linters:
          - unused
        path: magefiles/* # Exclude magefiles from unused checks as build targets are not imported
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/jacobbrewer1)
      custom-order: true
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
