// Code generated by mockery. DO NOT EDIT.

package web

import mock "github.com/stretchr/testify/mock"

// MockStartOption is an autogenerated mock type for the StartOption type
type MockStartOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockStartOption) Execute(_a0 *App) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*App) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockStartOption creates a new instance of MockStartOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStartOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStartOption {
	mock := &MockStartOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
