// Code generated by mockery. DO NOT EDIT.

package cache

import mock "github.com/stretchr/testify/mock"

// MockHashBucket is an autogenerated mock type for the HashBucket type
type MockHashBucket struct {
	mock.Mock
}

// InBucket provides a mock function with given fields: key
func (_m *MockHashBucket) InBucket(key string) bool {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for InBucket")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewMockHashBucket creates a new instance of MockHashBucket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashBucket(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashBucket {
	mock := &MockHashBucket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
