// Code generated by mockery. DO NOT EDIT.

package health

import mock "github.com/stretchr/testify/mock"

// MockCheckerOption is an autogenerated mock type for the CheckerOption type
type MockCheckerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockCheckerOption) Execute(_a0 *Checker) {
	_m.Called(_a0)
}

// NewMockCheckerOption creates a new instance of MockCheckerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckerOption {
	mock := &MockCheckerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
