// Code generated by mockery. DO NOT EDIT.

package health

import mock "github.com/stretchr/testify/mock"

// MockCheckerOption is an autogenerated mock type for the CheckerOption type
type MockCheckerOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockCheckerOption) Execute(_a0 *checker) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*checker) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockCheckerOption creates a new instance of MockCheckerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckerOption {
	mock := &MockCheckerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
